PCMS/PCMS/PCMS/Areas/Weigh/Controllers/md_order_WeighingController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PCMS.Areas.Weigh.Models;
using PagedList;
using Microsoft.Reporting.WebForms;
using System.Runtime.InteropServices;
using PCMS.Helper;
using System.IO;
using System.Drawing;

namespace PCMS.Areas.Weigh.Controllers
{
    [Authorize]
    public class md_order_WeighingController : Controller
    {
        private WeighContext db = new WeighContext();
        private Material.Models.MaterialContext MaterialContext = new Areas.Material.Models.MaterialContext();
        private MasterData.Models.MasterDataContext MasterDataContext = new Areas.MasterData.Models.MasterDataContext();
        private System.IO.Ports.SerialPort port;
        private byte[] UserSign = null;
        private long? UserSignId = null;
        // GET: Weigh/md_order_Weighing
        [LogActionFilter]
        public ActionResult Index(PCMS.Models.PaginationModel pg)
        {
            DateTime regDate = DateTime.Now;
            // Auf dem Server:
            // var model = db.Md_order_Weighing.Include(m => m.Weight1).Include(m => m.Weight2).OrderByDescending(m => m.RegistrationDate).Where(m => m.RegistrationDate.Year == regDate.Year && m.RegistrationDate.Month == regDate.Month && m.RegistrationDate.Day == regDate.Day).ToList();

            // Waage 1:
            var model = db.Md_order_Weighing.Include(m => m.Weight1).Include(m => m.Weight2).OrderByDescending(m => m.RegistrationDate).Where(m => m.RegistrationDate.Year == regDate.Year && m.RegistrationDate.Month == regDate.Month && m.RegistrationDate.Day == regDate.Day && (m.Weight1.ScaleNo == 1 || m.Weight1.ScaleNo == 0) && (m.Weight2.ScaleNo == 1 || m.Weight2.ScaleNo == 0)).ToList();

            // Waage 2:
            //var model = db.Md_order_Weighing.Include(m => m.Weight1).Include(m => m.Weight2).OrderByDescending(m => m.RegistrationDate).Where(m => m.RegistrationDate.Year == regDate.Year && m.RegistrationDate.Month == regDate.Month && m.RegistrationDate.Day == regDate.Day && (m.Weight1.ScaleNo == 2 || m.Weight1.ScaleNo == 0) && (m.Weight2.ScaleNo == 2 || m.Weight2.ScaleNo == 0)).ToList();

            // Waage 3:
            //var model = db.Md_order_Weighing.Include(m => m.Weight1).Include(m => m.Weight2).OrderByDescending(m => m.RegistrationDate).Where(m => m.RegistrationDate.Year == regDate.Year && m.RegistrationDate.Month == regDate.Month && m.RegistrationDate.Day == regDate.Day && (m.Weight1.ScaleNo == 3 || m.Weight1.ScaleNo == 0) && (m.Weight2.ScaleNo == 3 || m.Weight2.ScaleNo == 0)).ToList();

            return View(model.ToPagedList((pg.page ?? 1), pg.pageSize ?? PCMS.Helper.Definitions.pageSize));
        }
        [LogActionFilter]
        public ActionResult SelectDate(DateTime regDate, int state)
        {
            //var modelLoading = db.Md_order_LoadingOrder.Where(m => m.RegistrationDate.Value.Year == regDate.Year && m.RegistrationDate.Value.Month == regDate.Month && m.RegistrationDate.Value.Day == regDate.Day).OrderBy(a => a.Sort).ToList();
            if(state == 3)
            {
                // Server:
                //var model = db.Md_order_Weighing.Include(m => m.Weight1).Include(m => m.Weight2).OrderByDescending(m => m.RegistrationDate).Where(m => m.RegistrationDate.Year == regDate.Year && m.RegistrationDate.Month == regDate.Month && m.RegistrationDate.Day == regDate.Day).ToList();

                // Waage 1:
                var model = db.Md_order_Weighing.Include(m => m.Weight1).Include(m => m.Weight2).OrderByDescending(m => m.RegistrationDate).Where(m => m.RegistrationDate.Year == regDate.Year && m.RegistrationDate.Month == regDate.Month && m.RegistrationDate.Day == regDate.Day && (m.Weight1.ScaleNo == 1 || m.Weight1.ScaleNo == 0) && (m.Weight2.ScaleNo == 1 || m.Weight2.ScaleNo == 0)).ToList();

                // Waage 2:
                //var model = db.Md_order_Weighing.Include(m => m.Weight1).Include(m => m.Weight2).OrderByDescending(m => m.RegistrationDate).Where(m => m.RegistrationDate.Year == regDate.Year && m.RegistrationDate.Month == regDate.Month && m.RegistrationDate.Day == regDate.Day && (m.Weight1.ScaleNo == 2 || m.Weight1.ScaleNo == 0) && (m.Weight2.ScaleNo == 2 || m.Weight2.ScaleNo == 0)).ToList();

                // Waage 3:
                //var model = db.Md_order_Weighing.Include(m => m.Weight1).Include(m => m.Weight2).OrderByDescending(m => m.RegistrationDate).Where(m => m.RegistrationDate.Year == regDate.Year && m.RegistrationDate.Month == regDate.Month && m.RegistrationDate.Day == regDate.Day && (m.Weight1.ScaleNo == 3 || m.Weight1.ScaleNo == 0) && (m.Weight2.ScaleNo == 3 || m.Weight2.ScaleNo == 0)).ToList();

                return View("IndexContent", model.ToPagedList(1, PCMS.Helper.Definitions.pageSize));
            }
            else if (state == -1)
            {
                var model = db.Md_order_Weighing.Include(m => m.Weight1).Include(m => m.Weight2).OrderByDescending(m => m.RegistrationDate).Where(m => m.RegistrationDate.Year == regDate.Year && m.RegistrationDate.Month == regDate.Month && m.RegistrationDate.Day == regDate.Day && m.Status < 2).ToList();
                return View("IndexContent", model.ToPagedList(1, PCMS.Helper.Definitions.pageSize));
            }
            else
            {
                var model = db.Md_order_Weighing.Include(m => m.Weight1).Include(m => m.Weight2).OrderByDescending(m => m.RegistrationDate).Where(m => m.RegistrationDate.Year == regDate.Year && m.RegistrationDate.Month == regDate.Month && m.RegistrationDate.Day == regDate.Day && m.Status == state).ToList();
                return View("IndexContent", model.ToPagedList(1, PCMS.Helper.Definitions.pageSize));
            }
        }
        // GET: Weigh/md_order_Weighing/Details/5
        [LogActionFilter]
        public ActionResult Details(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            md_order_Weighing md_order_Weighing = db.Md_order_Weighing.Find(id);
            if (md_order_Weighing == null)
            {
                return HttpNotFound();
            }
            if (md_order_Weighing.WeightId1 != null)
            {
                md_order_Weighing.Weight1 = db.md_Weigh.Find(md_order_Weighing.WeightId1);
            }
            SelectListItem se = new SelectListItem() { Text = "Eingang", Value = "0" };
            SelectListItem se2 = new SelectListItem() { Text = "Ausgang", Value = "1" };
            SelectListItem se3 = new SelectListItem() { Text = "Barverkauf", Value = "2" };
            List<SelectListItem> seL = new List<SelectListItem>() { se, se2, se3 };
            ViewBag.Direction = new SelectList(seL, "Value", "Text", md_order_Weighing.Direction);
            return View(md_order_Weighing);
        }

        // GET: Weigh/md_order_Weighing/Create
        [LogActionFilter]
        public ActionResult Create()
        {
            SelectListItem se = new SelectListItem() { Text = "Eingang", Value = "0" };
            SelectListItem se2 = new SelectListItem() { Text = "Ausgang", Value = "1" };
            SelectListItem se3 = new SelectListItem() { Text = "Barverkauf", Value = "2" };
            List<SelectListItem> seL = new List<SelectListItem>() { se, se2, se3 };
            ViewBag.Direction = new SelectList(seL, "Value", "Text");
            return View();
        }

        // POST: Weigh/md_order_Weighing/Create
        // Aktivieren Sie zum Schutz vor übermäßigem Senden von Angriffen die spezifischen Eigenschaften, mit denen eine Bindung erfolgen soll. Weitere Informationen 
        // finden Sie unter http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [LogActionFilter]
        public ActionResult Create([Bind(Include = "Id,LicensePlate,RegistrationDate,WeightId1,WeightId2,CustomerDescription,CustomerId,ConstructionSiteDescription,ConstructionSiteId,ArticleDescription,OrderNumber,ArticleId,Direction,UserName1,UserName2,VehicleTaraWeight,VehicleType,CustomerStreet,CustomerCity,CustomerZIPCode,ConstructionSiteStreet,ConstructionSiteCity,ConstructionSiteZIPCode,ArticleNumber,ArticlePrice,ContingentNumber,Comment,Status,SealNumber,FuelTank,ContainerNo,AVVDescription,AVVNumber,ProducerId,ProducerDescription,ProducerStreet,ProducerCity,ProducerZIPCode,ProducerDateTime,ProducerNumber,CarrierId,CarrierDescription,CarrierStreet,CarrierCity,CarrierZIPCode,CarrierDateTime,CarrierNumber,DisposalId,DisposalDescription,DisposalStreet,DisposalCity,DisposalZIPCode,DisposalDateTime,DisposalNumber,DisposalProofNumber,VehicleNumber,EvenDelivery,EvenPickingUp,PickUpConatiner,UpContainer,Signature1Id,Signature2Id,Signature3Id, CustomerNumber, ConstructionSiteNumber")] md_order_Weighing md_order_Weighing, bool? print)
        {

            if (ModelState.IsValid)
            {
                md_order_Weighing.InvoiceCreated = false;
                md_order_Weighing.LicensePlate = md_order_Weighing.LicensePlate.ToUpper();
                md_order_Weighing.RegistrationDate = DateTime.Now;
                md_order_Weighing.Status = setStatus(md_order_Weighing);
                md_order_Weighing.UserName1 = User.Identity.Name;
                
                //md_order_Weighing.Signature1Id = lastSignature;

                if (md_order_Weighing.WeightId1 != null)
                {
                    md_order_Weighing.Status = 1;//1.Wägung
                   
                }
                if (md_order_Weighing.WeightId1 != null && md_order_Weighing.WeightId2 != null)
                {
                    md_order_Weighing.Status = 2;//2.Wägung
                   
                }

                // Manuelle Tara Eintrag Erstwiegung wird direkt als PT (-1) eingetragen

PCMS/PCMS/PCMS/Areas/Weigh/Views/md_order_Weighing/ChooseVehicle.cshtml
@model PagedList.IPagedList<PCMS.Areas.MasterData.Models.md_masterData_Vehicle>
@using PagedList.Mvc
<div class="tableContent" tablename="md_masterData_Vehicle">
    <link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />
    @{
        ViewBag.Title = "Fahrzeug Auswahl";
        Layout = "~/Views/Shared/_Layout.cshtml";
        if (Request.IsAjaxRequest())
        {
            Layout = null;
        }
    }
    @Html.Partial("~/Views/Shared/Partial_Paging.cshtml", Model)
    <div style="overflow-x: auto;">
        <table url="@Url.Action("ChooseVehicle","md_order_Weighing", new { area = "Weigh" } )" class="table table-hover table-condensed" tablename="md_masterData_Vehicle">
            <thead>
                <tr class="caption">
                    <th editable="false" colname="Id" style="display:none">@Html.DisplayNameFor(model => model[0].Id)</th>
                    <th editable="false" colname="VehicleNumber" style="">@Html.DisplayNameFor(model => model[0].VehicleNumber)</th>
                    <th editable="true" colname="PlateNumber" style="">@Html.DisplayNameFor(model => model[0].PlateNumber)</th>
                    <th editable="true" colname="Capacity" style="">@Html.DisplayNameFor(model => model[0].Capacity)</th>
                    <th editable="true" colname="Customer" style="">@Html.DisplayNameFor(model => model[0].Md_Customer.Name)</th>
                    <th editable="true" colname="DriverNumber" style="display:none">@Html.DisplayNameFor(model => model[0].md_masterData_Driver.DriverNumber)</th>
                    <th editable="true" colname="DriverName" style="display:none">@Html.DisplayNameFor(model => model[0].md_masterData_Driver.Md_masterData_Contact.LastName)</th>
                </tr>
                <tr>
                    <th style="display:none" class="head-filter" columnname="Id" tablename="md_masterData_Vehicle"></th>
                    <th style="" class="head-filter" columnname="VehicleNumber" tablename="md_masterData_Vehicle"><input class="head-filter-value form-control" onkeydown="headFilterKeyDownModal(event)" type="text" placeholder="Suchen" /></th>
                    <th style="" class="head-filter" columnname="PlateNumber" tablename="md_masterData_Vehicle"><input class="head-filter-value form-control" onkeydown="headFilterKeyDownModal(event)" type="text" placeholder="Suchen" /></th>
                    <th style="" class="head-filter" columnname="TareWeight" tablename="md_masterData_Vehicle"><input class="head-filter-value form-control" onkeydown="headFilterKeyDownModal(event)" type="text" placeholder="Suchen" /></th>
                    <th style="" class="head-filter" columnname="Customer" tablename="md_masterData_Vehicle"><input class="head-filter-value form-control" onkeydown="headFilterKeyDownModal(event)" type="text" placeholder="Suchen" /></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr id="@item.Id" onclick="chooseVehi(this)">
                        <td columnname="Id" style="display:none" tablename="md_masterData_Vehicle">@Html.DisplayFor(modelItem => item.Id)</td>
                        <td columnname="VehicleNumber" style="" tablename="md_masterData_Vehicle">@Html.DisplayFor(modelItem => item.VehicleNumber)</td>
                        <td columnname="PlateNumber" style="" tablename="md_masterData_Vehicle">@Html.DisplayFor(modelItem => item.PlateNumber)</td>
                        <td columnname="Capacity" style="" tablename="md_masterData_Vehicle">@Html.DisplayFor(modelItem => item.Capacity)</td>
                        <td columnname="Customer" style="" tablename="md_masterData_Vehicle">@Html.DisplayFor(modelItem => item.Md_Customer.Name)</td>
                        <td columnname="DriverNumber" style="display:none" tablename="md_masterData_Vehicle">@Html.DisplayFor(modelItem => item.md_masterData_Driver.DriverNumber)</td>
                        <td columnname="DriverName" style="display:none" tablename="md_masterData_Vehicle">@Html.DisplayFor(modelItem => item.md_masterData_Driver.Md_masterData_Contact.LastName)</td>
                        <td columnname="EmptyingProgram" style="display:none" tablename="md_masterData_Vehicle">@Html.DisplayFor(modelItem => item.EmptyingProgram)</td>
                        <td columnname="Type" style="display:none" tablename="md_masterData_Vehicle">@Html.DisplayFor(modelItem => item.Md_masterData_VehicleType.Description)</td>
                        <td columnname="TareWeight" style="display:none" tablename="md_masterData_Vehicle">@Html.DisplayFor(modelItem => item.TareWeight)</td>

                        <td columnname="CustomerName" style="display:none" tablename="md_masterData_Vehicle">@Html.DisplayFor(modelItem => item.Md_Customer.Name)</td>
                        <td columnname="CustomerStreet" style="display:none" tablename="md_masterData_Vehicle">@Html.DisplayFor(modelItem => item.Md_Customer.Md_masterData_Address.Street)</td>
                        <td columnname="CustomerCity" style="display:none" tablename="md_masterData_Vehicle">@Html.DisplayFor(modelItem => item.Md_Customer.Md_masterData_Address.City)</td>
                        <td columnname="CustomerZipCode" style="display:none" tablename="md_masterData_Vehicle">@Html.DisplayFor(modelItem => item.Md_Customer.Md_masterData_Address.ZipCode)</td>
                        <td columnname="CustomerId" style="display:none" tablename="md_masterData_Vehicle">@Html.DisplayFor(modelItem => item.Md_Customer.Id)</td>
                        

                    </tr>
                }
            </tbody>
        </table>
    </div>
    @Html.Partial("~/Views/Shared/Partial_Paging.cshtml", Model)
</div>

<script>
    function chooseVehi(e) {
        $("#VehicleNumber").val($(e).closest("tr").find("td[columnname='VehicleNumber']").text().trim());
        //Waagen

        $("#LicensePlate").val($(e).closest("tr").find("td[columnname='PlateNumber']").text().trim());
        $("#VehiclePlateNo").val($(e).closest("tr").find("td[columnname='PlateNumber']").text().trim());
        $("#VehicleType").val($(e).closest("tr").find("td[columnname='Type']").text().trim());
        $("#DriverNumber").val($(e).closest("tr").find("td[columnname='DriverNumber']").text().trim());
        $("#DriverName").val($(e).closest("tr").find("td[columnname='DriverName']").text().trim());
        $("#EmptyingProgram").val($(e).closest("tr").find("td[columnname='EmptyingProgram']").text().trim());
        $("#VehicleNumber").val($(e).closest("tr").find("td[columnname='VehicleNumber']").text().trim());
        

        $("#VehicleTaraWeight").val($(e).closest("tr").find("td[columnname='TareWeight']").text().trim());

        $("#CustomerDescription").val($(e).closest("tr").find("td[columnname='CustomerName']").text().trim());
        $("#CustomerStreet").val($(e).closest("tr").find("td[columnname='CustomerStreet']").text().trim());
        $("#CustomerCity").val($(e).closest("tr").find("td[columnname='CustomerCity']").text().trim());
        $("#CustomerZIPCode").val($(e).closest("tr").find("td[columnname='CustomerZipCode']").text().trim());
        $("#CustomerId").val($(e).closest("tr").find("td[columnname='CustomerId']").text().trim());


        //$("#ConstructionSiteNumber").val(null);
        //$("#ConstructionSiteDescription").val(null);
        //$("#ConstructionSiteStreet").val(null);
        //$("#ConstructionSiteCity").val(null);
        //$("#ConstructionSiteZIPCode").val(null);
        //$("#ConstructionSiteId").val(null);

        getCustomer($(e).closest("tr").find("td[columnname='CustomerId']").text().trim());

        if ($(e).closest("tr").find("td[columnname='CustomerId']").text().trim().length > 0 && false) {
            var CustomerId = $(e).closest("tr").find("td[columnname='CustomerId']").text().trim();
            $.post("/Weigh/md_order_Weighing/CheckConstructionSite", { id: CustomerId }, function (data) {
                if (data == true) {
                    $.post("/Weigh/md_order_Weighing/ChooseConstructionSite", { id: CustomerId }, function (data) { chooseConstruction("Baustelle auswählen", data, ["", ""]); });
                }
                else {
                    $.post("/Weigh/md_order_Weighing/SelectConstructionSite", { id: CustomerId }, function (data) {
                        if (data.Name != "") {
                            $("#ConstructionSiteNumber").val(data.ConId).text();
                            $("#ConstructionSiteDescription").val(data.Name).text();
                            $("#DistanceTime").val(data.Distance).text();
                        }
                    });
                }
            })
        }
        

        $("#Modal").modal("hide");
    }
</script>

PCMS/PCMS/PCMS/Areas/Weigh/Views/md_order_Weighing/Create.cshtml
@model PCMS.Areas.Weigh.Models.md_order_Weighing

@{
    ViewBag.Title = "Neue Wiegung";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<style>
    .uppercase {
        text-transform: uppercase;
    }
</style>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    @Html.Partial("~/Views/Shared/Partial_Cancel_Create_t.cshtml", new ViewDataDictionary { { "SaveAndReport", "/Weigh/md_order_Weighing/ReportDetail/" } })
    @Html.Partial("Content", Model)
    @Html.Partial("~/Views/Shared/Partial_Cancel_Create_b.cshtml")
}

<script>
   
</script>

@*@section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }*@

PCMS/PCMS/PCMS/Areas/Weigh/Views/md_order_Weighing/CreateManuell.cshtml
@model PCMS.Areas.Weigh.Models.md_order_Weighing

@{
    ViewBag.Title = "Nacherfassen";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<style>
    .uppercase {
        text-transform: uppercase;
    }
</style>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    @Html.Partial("~/Views/Shared/Partial_Cancel_Save_t.cshtml", new ViewDataDictionary { { "SaveAndReport", "/Weigh/md_order_Weighing/ReportDetail/" } })
    @Html.Partial("ContentManuell", Model)
    @Html.Partial("~/Views/Shared/Partial_Cancel_Create_b.cshtml")
}

<script>

</script>

PCMS/PCMS/PCMS/Areas/Weigh/Views/md_order_Weighing/Details.cshtml
@model PCMS.Areas.Weigh.Models.md_order_Weighing

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm())
{


    @Html.HiddenFor(model => model.Id)
    @Html.HiddenFor(model => model.RegistrationDate)
    @Html.HiddenFor(model => model.UserName1)
    @Html.HiddenFor(model => model.UserName2)
    @Html.HiddenFor(model => model.ContingentNumber)
    @Html.HiddenFor(model => model.Status)


    @Html.AntiForgeryToken()
    <div class="row">
        <div class="col-md-7"><a class="btn btn-default" href="/Weigh/md_order_Weighing"><i class="fa fa-times"></i> Abbrechen</a></div>        
        <div class="col-md-1"><button id="getReportBtn" type="button" url="/Weigh/md_order_Weighing/ReportDetail/" class="getReportBtn btn btn-default"><i class="fa fa-file-text-o"></i> Anzeigen</button></div>
        <div class="col-md-1"><button id="getReportBtnPrint" type="button" url="/Weigh/md_order_Weighing/ReportDetailPrint/" class="getReportBtnPrint btn btn-default btn-succsess"><i class="fa fa-file-text-o"></i> Drucken</button></div>
        @*<div class="col-md-1"><button id="getReportBtn" type="button" url="/Weigh/md_order_Weighing/ReportDetailSolas/" class="getReportBtn btn btn-default"><i class="fa fa-file-text-o"></i> Report Solas</button></div>*@
    </div>
    <hr />
    @Html.Partial("Content", Model)
   <hr/>
    <div class="row">
        <div class="col-md-7"><a class="btn btn-default" href="/Weigh/md_order_Weighing"><i class="fa fa-times"></i> Abbrechen</a></div>
        <div class="col-md-1"><button id="getReportBtn" type="button" url="/Weigh/md_order_Weighing/ReportDetail/" class="getReportBtn btn btn-default"><i class="fa fa-file-text-o"></i> Drucken</button></div>


    </div>
}
<script type="text/javascript" >
    var editAble = false;
</script>

PCMS/PCMS/PCMS/Areas/Weigh/Views/md_order_Weighing/choosMaterial.cshtml
@model PagedList.IPagedList<PCMS.Areas.MasterData.Models.md_masterData_Material>
@using PagedList.Mvc
@{
    ViewBag.Title = "Zuschlagstoffe Übersicht";
    Layout = null;
}

<div class="tableContent" tablename="md_masterData_Material">
    <link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />



    @Html.Partial("~/Views/Shared/Partial_Paging.cshtml", Model)
    <div style="overflow-x: auto;">

        <table url="@Url.Action("choosMaterial","md_order_Weighing", new { area = "Weigh" } )" class="table table-hover table-condensed" tablename="md_masterData_Material" editUrl="@Url.Action("EditAggregates", "md_recipe_Recipe", new { area = "Recipe" })" deleteUrl="@Url.Action("Delete", "md_recipe_Recipe", new { area = "Recipe" })">
            <thead>
                <tr class="caption">
                    <th ondblclick="hideColumn(this)" onclick="sort(this)" editable="false" colname="Id" style="">
                        @Html.DisplayNameFor(model => model[0].Id)
                    </th>
                    <th ondblclick="hideColumn(this)" onclick="sort(this)" editable="true" colname="Name" style="">
                        @Html.DisplayNameFor(model => model[0].Name)
                    </th>
                    <th ondblclick="hideColumn(this)" onclick="sort(this)" editable="true" colname="ShortName" style="">
                        @Html.DisplayNameFor(model => model[0].ShortName)
                    </th>
                    <th editable="true" onclick="sort(this)" colname="ArticleNumber" style="">
                        @Html.DisplayNameFor(model => model[0].ArticleNumber)
                    </th>
                    <th>
                        MaterialArt
                    </th>
                    <th>

                    </th>
                </tr>
                <tr>
                    <th style="" class="head-filter" columnname="Id" tablename="md_masterData_Material">
                    </th>
                    <th style="" class="head-filter" columnname="Name" tablename="md_masterData_Material">
                        <input class="head-filter-value form-control" onkeydown="headFilterKeyDownModal(event)" type="text" value="@ViewBag.Name"/>
                    </th>
                    <th style="" class="head-filter" columnname="ShortName" tablename="md_masterData_Material">
                        <input class="head-filter-value form-control" onkeydown="headFilterKeyDownModal(event)" type="text" value="@ViewBag.ShortName"/>
                    </th>
                    <th style="" class="head-filter" columnname="ArticleNumber" tablename="md_masterData_Material">
                        <input class="head-filter-value form-control" onkeydown="headFilterKeyDownModal(event)" type="text" value="@ViewBag.ArticleNumber"/>
                    </th>
                    <th style="" class="head-filter" columnname="MaterialGroupId" tablename="md_masterData_Material">
                        @Html.DropDownList("MaterialGroup", null, "---Bitte wählen---", htmlAttributes: new { @class = "form-control", @onchange = "headFilterChangeModal(this)", @columnname = "MaterialGroupId" })
                    </th>
                </tr>
            </thead>

            <tbody>
                @foreach (var item in Model)
                {
                    <tr onclick="getMaterialById(this)" id="@item.Id" materialtypeTT="@item.MaterialGroupId">
                        <td class="" columnname="Id" style="" tablename="md_masterData_Material">
                            @Html.DisplayFor(modelItem => item.Id)
                        </td>
                        <td class="" columnname="Lastname" style="" tablename="md_masterData_Material">
                            @Html.DisplayFor(modelItem => item.Name)
                        </td>
                        <td class="" columnname="Firstname" style="" tablename="md_masterData_Material">
                            @Html.DisplayFor(modelItem => item.ShortName)
                        </td>
                        <td class="" columnname="Street" style="" tablename="md_masterData_Material">
                            @Html.DisplayFor(modelItem => item.ArticleNumber)
                        </td>
                        <td class="" columnname="Price" style="display:none" tablename="md_masterData_Material">
                            @Html.DisplayFor(modelItem => item.Price)
                        </td>
                        <td>
                            <button onclick="getMaterialById(this)">hinzufügen</button>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
    @Html.Partial("~/Views/Shared/Partial_Paging.cshtml", Model)
</div>
<script type="text/javascript" >
   
</script>